### ISSUE TITLE
Support Chevereto

### ISSUE THREAD

**Issue by rodber** [deontic/imgBB-web-bulk-downloader#2]
Hey @deontic 

In case you didn't know, imgbb is based on a software known as [Chevereto](https://github.com/chevereto). If you make your system Chevereto-compatible you will support ImgBB plus all the systems using Chevereto (near 10K installations).

Hope you give it a try, enjoy your new users ;)

**Comment by deontic** [comment]
Hi,
I assumed it was based off of some sort of framework but didn't intend to support all systems using it since I didn't expect significant usage anyway (an assumption that proved true). I will attempt to make a version that is Chevereto-compatible now anyway though. Thanks.

**Comment by deontic** [comment]
should be working for all sites that allow automated requests
https://github.com/deontic/chevereto-bulk-downloader
